# Generated by Django 5.1.1 on 2024-10-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('director', models.TextField()),
                ('cast', models.TextField()),
                ('genre', models.TextField()),
                ('duration', models.IntegerField()),
                ('year', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('awards', models.TextField()),
                ('trailer', models.TextField()),
                ('review', models.TextField()),
            ],
        ),
    ]
