# Generated by Django 5.1.1 on 2024-10-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_actor_reviewer_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='url dkposter.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Reviewer',
        ),
    ]
