# Generated by Django 5.1.1 on 2024-10-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_actor_movie_image_movie_rating_delete_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='dkposter.jpg', upload_to=''),
        ),
    ]
