# Generated by Django 5.1.1 on 2024-10-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='dkposter.jpg', upload_to='movie_posters'),
        ),
    ]
