# Generated by Django 5.1.1 on 2024-10-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='review',
        ),
    ]
